quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
This is a fix for the problem I reported in QFJ_822.
When a connection attempt fails, it clears the cached DNS resolution information so that the next connection attempt will repeat the resolution -- thereby picking up any DNS changes for the host.
=> QFJ-822 Refresh DNS resolution info on connection error.

quickfixj-core/src/main/java/quickfix/field/converter/UtcTimestampConverter.java
http://www.quickfixj.org/jira/browse/QFJ-823
fixing problem with concurrent access to UtcTimestampConverter#dateCache
=> Troshanin patch qfj 823

.gitignore, pom.xml, quickfixj-core/pom.xml, quickfixj-dictgenerator/pom.xml, quickfixj-examples/pom.xml
* Bump Slf4J to 1.7.10 (1.7.5 is the recommended version for Java 6+ which has improvements for getting logger instances faster)
* Bump few other non relevant dependencies like HSQL and Jaxen (Minor fixes)
* Added entries to .gitignore file for IntelliJ.
=> Bump Slf4J and few other dependencies and .gitignore entries for IntelliJ.

quickfixj-core/pom.xml
* JUnit upgraded to 4.10, can't do 4.11+ for now due to order of execution for Java 7+, which can be fixed by annotating each test class though it is tedious to do so now, might be done later when I have more time.
* Mockito upgraded to latest stable which made me gain some tests performace; used to take almost 13 minutes on my laptop to do `mvn clean test` and now it is taking a little bit less than 12 minutes.
=> Bump JUnit and Mockito dependencies.

quickfixj-core/pom.xml
This should had been included in my previous bump deps branch, or I just noticed such version was available on Maven central.
=> Apache mina-core bump to 2.0.9

pom.xml, quickfixj-codegenerator/pom.xml, quickfixj-core/pom.xml, quickfixj-distribution/pom.xml
Bump Maven plugins version, except for `maven-assembly-plugin` which latest version 2.5.3 has a bug and hence was bumped only to 2.5.2, bug described below:
https://jira.codehaus.org/browse/MASSEMBLY-747
=> Bump Maven plugins version

quickfixj-core/pom.xml, quickfixj-messages/pom.xml
Maven -Dgenerator.decimal=true will generate classes using BigDecimal.
@chrjohn The other 2 pull requests I sent I can assure you they are harmless and a good thing, for example, IntelliJ has done its best effort to migrate specific classes to use proper Java 6 which is the minimum requirement for QuickFixJ 1.6+
And forcing maven to 3.2.5 is not a bad thing either, Maven 3.3.1 was released so that would be the latest 3.2.x as requirement which does a better job than 3.0.x or 3.1.x
Is there any other parameter that needs to be fixed that isn't working when the project was migrated from Ant to Maven?
As for BigDecimal, in this branch it keeps the default value which is false but this is something that nobody would recommend for financial applications.
=> Maven -Dgenerator.decimal=true will generate classes using BigDecimal

pom.xml
Update pre-requisite to latest Maven, this will force contributors to use latest Maven which could be a hassle to update but the benefit is that it will also inherit newer plugins overall, also less whole system overload while building QuickFixJ.
=> Bump Maven version to 3.2.5

quickfixj-core/src/main/java/quickfix/mina/initiator/InitiatorIoHandler.java
- There are (at least) 2 threads at each host.
- IO thread : Receives a message from an opposite and put it onto queue.
- Application thread : Takes the message from the queue and processes it.
- Probelm in the original implementation
- At initiator side, _Application thread_ sets default application version ID when receiving a first LOGON message.
- IO thread needs default application version ID to be set to parse incoming messages.
- If IO thread attempts to parse a message before Application thread sets default application version ID, it causes error.
- Fixed version
- At initiator side, _IO thread_ sets default application version ID when receiving a first LOGON message.
- By the way, at acceptor side, IO thread sets default application version ID from the beginning.
=> Fix timing to set default application version ID at initiator side

quickfixj-core/src/main/java/quickfix/Session.java
This means we can query this flag in the toAdmin callback.
=> Moving the setLogoutReceived flag to before we generate a logout response

pom.xml, quickfixj-codegenerator/pom.xml, quickfixj-core/pom.xml, quickfixj-distribution/pom.xml
Maven plugins updated and compiler `fork=true` option removed because it breaks the build, also, Maven prerequisite updated to latest 3.3.3 to keep default plugins at latest required versions.
All other pending pull requests should build properly after this one is merged, excluding Travis which should be set to Oracle JDK 7 which won't interfere with JDK 6 requirement of the project but will build faster due to JDK 7 performance vs JDK 6.
**Note:** Apache Felix bundle plugin makes build fail if updated to 2.5.4, so I left it at 2.5.3
=> Maven plugins updated and compiler fork=true option removed

pom.xml, quickfixj-codegenerator/pom.xml, quickfixj-core/pom.xml
Updated Maven plugins, Slf4j & Mina core which fixes some SSL bugs.
It might fix the QFJ SSL bugs, look at Mina core release notes at https://mina.apache.org/mina-project/index.html
Listed below for the lazy:
```
Bugs :
DIRMINA-992 - NioSocketConnector.newHandle throws the wrong exception
DIRMINA-994 - The ConnectionRequest.cancel() method is inconsistent wrt concurrent access
DIRMINA-995 - Deadlock when using SSL and proxy
DIRMINA-1013 -Threading model is supressed by ProtocolCodecFilter
DIRMINA-1016 - Regression with 2.0.9: Missing javax.net.ssl import in manifest
DIRMINA-1017 - SSLEngine BUFFER_OVERFLOW (unwrap)
DIRMINA-1019 - SslHandler flushScheduledEvents race condition
Improvements :
DIRMINA-1018 - fetchAppBuffer shrink
DIRMINA-1020 - Change minimum version for slf4j in MANIFEST …
```
=> Update Maven plugins, Slf4j & Mina core which fixes some SSL bugs

pom.xml
Maven bundle set to 2.5.3 for JDK6 support, branch based on 1.6.x
=> Maven bundle plugin downgraded to 2.5.3 for JDK6

quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
This is a minor rework of a pull request submitted last January (https://github.com/quickfix-j/quickfixj/pull/7)  
The January request was originally merged but had to be reverted since it would not compile under jdk1.6.
I've done a (very minor) rework and it should build with Java 6 now.
Thanks
=> Fix for QFJ-822: Reset cached DNS resolution information after a connection failure.

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
Corrected sequence number of last gap fill after all app messages have been sent in a resend request when the session is set up to not store admin messages
=> QFJ-730 Corrected sequence number of last gap fill 

quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java
remove dup
if (settings.isSetting(sessionID, Session.SETTING_VALIDATE_UNORDERED_GROUP_FIELDS)) {
dataDictionary.setCheckUnorderedGroupFields(settings.getBool(sessionID,
Session.SETTING_VALIDATE_UNORDERED_GROUP_FIELDS));
}
=> remove duplicate code

quickfixj-core/pom.xml
From https://mina.apache.org/mina-project/index.html
MINA 2.0.13 released posted on February, 16, 2016
Another release to fix a critical SSL bug ( a race condition which could lead to a deadlock in some corner cases).
We urge you to switch to this version if you were using MINA 2.0.12.
Bugs :
DIRMINA-1019 SslHandler flushScheduledEvents race condition
DIRMINA-1027 SSLHandler writes corrupt messages under heavy load
=> Mina-core to 2.0.13

pom.xml, quickfixj-core/src/main/java/quickfix/SessionID.java, quickfixj-core/src/main/java/quickfix/SessionSettings.java, quickfixj-core/src/main/java/quickfix/SystemTime.java, quickfixj-core/src/main/java/quickfix/field/converter/DoubleConverter.java, quickfixj-core/src/test/java/quickfix/test/acceptance/ExpectMessageStep.java
**Small changes:**
- Synchronization of time in millis removed.
- Regex compiled pattern made static.
- Slf4j updated to 1.7.18
=> QFJ-879: Small Changes: Static compiled pattern, un-sync time and slf4j update

pom.xml, quickfixj-core/src/main/java/quickfix/ThreadedSocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java, quickfixj-core/src/main/java/quickfix/mina/IoSessionResponder.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java, quickfixj-core/src/test/java/quickfix/mina/IoSessionResponderTest.java
Bump plugin versions, all tests passed, everything generated pretty fast which makes me think `javadoc-plugin` got better, or maybe just a placebo effect.
=> Fixes QFJ-895 for 1.7.x and bump plugin versions

quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix40/1b_DuplicateIdentity.def, quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix41/1b_DuplicateIdentity.def, quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix42/1b_DuplicateIdentity.def, quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix43/1b_DuplicateIdentity.def, quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix44/1b_DuplicateIdentity.def, quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix50/1b_DuplicateIdentity.def
- the tests will disconnect anyway when there are no more commands in the file
=> removed incorrect disconnect command from duplicate identity acceptance tests

pom.xml, quickfixj-core/src/main/java/quickfix/NoopStore.java, quickfixj-core/src/main/java/quickfix/NoopStoreFactory.java, quickfixj-core/src/test/java/quickfix/NoopStoreTest.java
Noop message store implementation.
=> Noop message store implementation

quickfixj-codegenerator/src/main/java/org/quickfixj/codegenerator/MessageCodeGenerator.java, quickfixj-core/src/main/java/org/quickfixj/SimpleCache.java, quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/ConnectorAdmin.java, quickfixj-core/src/main/java/quickfix/DefaultDataDictionaryProvider.java, quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java, quickfixj-core/src/main/java/quickfix/FileStore.java, quickfixj-core/src/main/java/quickfix/JdbcUtil.java, quickfixj-core/src/main/java/quickfix/SystemTime.java, quickfixj-core/src/main/java/quickfix/field/converter/UtcTimestampConverter.java, quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java, quickfixj-core/src/main/java/quickfix/mina/ThreadPerSessionEventHandlingStrategy.java, quickfixj-core/src/main/java/quickfix/mina/message/FIXMessageDecoder.java, quickfixj-core/src/test/java/quickfix/DefaultSessionFactoryTest.java, quickfixj-core/src/test/java/quickfix/LogUtilTest.java, quickfixj-core/src/test/java/quickfix/LoginTestCase.java, quickfixj-core/src/test/java/quickfix/SessionResetTest.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java, quickfixj-core/src/test/java/quickfix/mina/message/FIXMessageDecoderTest.java, quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java, quickfixj-core/src/test/java/quickfix/mina/ssl/SecureSocketTest.java, quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/ui/BanzaiFrame.java
Post jdk8 migration code refactor.
=> Post jdk8 migration code refactor.

quickfixj-core/src/main/java/org/quickfixj/SimpleCache.java
Concurrency levels for quick computing values should be a factor of CPUs, by default JDK sets it to 16 but this is not efficient when you have more CPUs.
=> Adjust SimpleCache concurrency level

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/Initiator.java, quickfixj-core/src/main/java/quickfix/mina/ProtocolFactory.java, quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/initiator/InitiatorProxyIoHandler.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
This patch add support for proxy for initiator connections.
It's tested and working with and without SSL
=> QFJ-285 Add proxy support (compatible with SSL)

quickfixj-core/src/main/java/quickfix/ExecutorFactory.java, quickfixj-core/src/main/java/quickfix/SocketAcceptor.java, quickfixj-core/src/main/java/quickfix/SocketInitiator.java, quickfixj-core/src/main/java/quickfix/ThreadedSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/ThreadedSocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java, quickfixj-core/src/main/java/quickfix/mina/ThreadPerSessionEventHandlingStrategy.java
**Purpose:**
To provide a mechanism for using externally supplied ThreadPools/Executors instead of the internal QFJ managed Threads.  Expected use case is for ResourceAdapter authors to inject the WorkManager (wrapped as an Executor).
**Solution:**
Defines a new quickfix.ExecutoryFactory interface and adds SessionConnector#setExecutorFactory(...) so that externally supplied Executors can be used.  One Executor is for the timer tasks and one for the message processing.
The Acceptors/Initiators pass the message processing Executor through to their EventHandlingStrategy.  The EventHandlingStrategy classes have been adapted to support the external Executor or fallback to the old behavior if no Executor is supplied.
**Compatibility:**
- There are no API breakages, only new optional API.
- The …
=> QFJ-912: Support use of externally supplied ThreadPools.

quickfixj-messages/quickfixj-messages-fix50sp1/src/main/resources/FIX50SP1.modified.xml, quickfixj-messages/quickfixj-messages-fix50sp1/src/main/resources/FIX50SP1.xml, quickfixj-messages/quickfixj-messages-fix50sp2/src/main/resources/FIX50SP2.modified.xml, quickfixj-messages/quickfixj-messages-fix50sp2/src/main/resources/FIX50SP2.xml
Affected files: FIX50SP1.modified.xml, FIX50SP2.modified.xml, FIX50SP1.xml, FIX50SP2.xml.
Affected value: <value enum=**"f "** description="FAST_MARKET_ETH"/>
I guess this whitespace is a typo.
=> Whitespace removed from field number=276 (QuoteCondition)

quickfixj-core/src/main/doc/usermanual/usage/configuration.html
TargetCompIDs are required and should not have an (optional) qualifier in the docs, here: http://www.quickfixj.org/quickfixj/usermanual/1.5.0/usage/configuration.html
=> removed '(optional)' qualifier for TargetCompID from configuration docs

quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java, quickfixj-core/src/main/java/quickfix/DefaultSessionSchedule.java, quickfixj-core/src/main/java/quickfix/DefaultSessionScheduleFactory.java, quickfixj-core/src/main/java/quickfix/SessionSchedule.java, quickfixj-core/src/main/java/quickfix/SessionScheduleFactory.java, quickfixj-core/src/test/java/quickfix/LogUtilTest.java, quickfixj-core/src/test/java/quickfix/SessionScheduleTest.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
Currently the scheduling options are weekly or daily or to use an external scheduler.
This allows a custom scheduler to be defined by the user by implementing the SessionSchedule interface.
=> Allow a custom SessionSchedule

quickfixj-core/src/main/java/quickfix/field/converter/DoubleConverter.java, quickfixj-core/src/test/java/quickfix/FieldConvertersTest.java
Benchmark                              Mode  Cnt        Score       Error  Units
DoubleConverterBenchmark.measureFast  thrpt   10  1204994.113 ± 11444.945  ops/s
DoubleConverterBenchmark.measureRaw   thrpt   10   575634.679 ±  6665.589  ops/s
=> optimize DoubleConverter

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/PausableThreadPoolExecutor.java, quickfixj-core/src/test/java/quickfix/SessionDisconnectConcurrentlyTest.java, quickfixj-core/src/test/java/quickfix/SessionResetTest.java
This is a variation of upchuck's pull request with a unit test to verify that the issue is fixed.
The gist of this pull request:
1.  Move logonReceived and logonSent local variables in Session.disconnect(String,boolean) to top of method
2.  Pull up PausableThreadPoolExecutor into its own top level class that can be leveraged by other test classes.
3.  Create unit test in SessionDisconnectConcurrentlyTest.  In order to get this problem to come out sometimes I have to bombard the disconnect method with a thousand threads while in the context of a for loop.
=> QFJ-917: multi-threaded disconnect fails to call onLogout (Take #2)

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java, quickfixj-core/src/test/java/quickfix/MessageTest.java
- extended Message.parseGroup() to accept unknown fields in repeating groups
- if validation is disabled (either completely or depending on ValidateUserDefinedFields or AllowUnknownMsgFields)
- if the field encountered is not a trailer or message field
- moreover, if validation is enabled, the incorrect field will be reported (not the next field that is encountered)
- added unit tests from QFJ issues
- removed synchronization from FieldException in Message since it seemed unnecessary
=> QFJ-169 / QFJ-791: support unknown tags in repeating groups

quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/BanzaiApplication.java, quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/Order.java, quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/ui/OrderTable.java
The type of `CumQty<14>` changed from `int` to `float` since FIX.4.2.
The banzai-example client assumes that `CumQty<14>` is an integer, leading to exceptions when the value has a fractional part:
<20170617-18:23:04, FIX.4.4:BANZAI->XXX, incoming> (8=FIX.4.4|9=147|35=8|49=XXX|56=BANZAI|34=2|43=N|52=20170617-18:23:04.033|55=USD|37=1497723783942|11=1497723783942|17=Test|150=B|39=0|54=1|151=0.0|14=0.0|6=0.0|10=153|)
java.lang.NumberFormatException: For input string: "0.0"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.parseInt(Integer.java:615)
at quickfix.examples.banzai.BanzaiApplication.executionReport(BanzaiApplication.java:221)
at …
=> Treating CumQty as a double value in Banzai

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
- corrected behaviour and added unit test
- minor refactoring: introduced method for logging "invalid message" and disconnecting
=> QFJ-929: FieldException on Logon message is handled incorrectly

quickfixj-core/src/main/java/quickfix/mina/ProtocolFactory.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
Fix proxy support with alternative socket hosts
Update http proxy to use CONNECT
=> QFJ-285 Proxy support fixes

quickfixj-core/src/main/java/quickfix/FileLog.java
Fixes thread race condition regression in http://www.quickfixj.org/jira/browse/QFJ-318. 1.4.0 seems to be the last released version with this fix.
See also: https://sourceforge.net/p/quickfixj/code/826/
=> QFJ-318 / QFJ-677 regression (FileLog thread safety)

quickfixj-codegenerator/pom.xml, quickfixj-codegenerator/src/main/java/org/quickfixj/codegenerator/MessageCodeGenerator.java, quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/Fields.xsl, quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/Message.xsl, quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/MessageFactory.xsl, quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/MessageSubclass.xsl
**Changes**
- use Saxon instead of Xalan for XSLT
- update all .xsl files to XSLT 2.0
- implement a sanitise description function which allows use of code generation with verbose data dictionaries
**Rationale**
Bloomberg have produced a data dictionary which is incompatible with the current codegenerator.   They have for example replaced
```xml
<field number="13" name="CommType" type="CHAR">
<value enum="1" description="PER_UNIT"/>
<value enum="2" description="PERCENTAGE"/>
<value enum="3" description="ABSOLUTE"/>
<value enum="4" description="PERCENTAGE_WAIVED_CASH_DISCOUNT"/>
<value enum="5" description="PERCENTAGE_WAIVED_ENHANCED_UNITS"/>
<value enum="6" description="POINTS_PER_BOND_OR_OR_CONTRACT"/>
</field>
```
with
```xml
<field number="13" name="CommType" type="CHAR">
<value …
```
=> Support data dictionaries with verbose descriptions

quickfixj-core/src/main/java/quickfix/Session.java
- prevent calling Session.resetState() concurrently
=> QFJ-923: FileStore is leaking file handles

pom.xml, quickfixj-core/pom.xml, quickfixj-distribution/pom.xml
- re-enabled generation of javadoc for FIX field and message classes
- if you do not want this, then -Dmaven.javadoc.skip=true is your friend :)
=> QFJ-914: Generate and package javadoc for release build

pom.xml, quickfixj-codegenerator/pom.xml, quickfixj-core/src/main/java/quickfix/FieldMap.java, quickfixj-core/src/main/java/quickfix/JdbcUtil.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/UtcTimeOnlyField.java, quickfixj-core/src/main/java/quickfix/UtcTimeStampField.java, quickfixj-core/src/main/java/quickfix/field/converter/UtcDateOnlyConverter.java, quickfixj-core/src/main/java/quickfix/field/converter/UtcTimeOnlyConverter.java, quickfixj-core/src/main/java/quickfix/field/converter/UtcTimestampConverter.java, quickfixj-core/src/main/java/quickfix/mina/ssl/X509TrustManagerWrapper.java, quickfixj-core/src/test/java/quickfix/SessionTest.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java, quickfixj-core/src/test/java/quickfix/mina/SingleThreadedEventHandlingStrategyTest.java, quickfixj-core/src/test/java/quickfix/mina/message/FIXMessageDecoderTest.java, quickfixj-dictgenerator/pom.xml, quickfixj-dictgenerator/src/main/java/org/quickfixj/dictgenerator/Repository.java, quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/ui/OrderEntryPanel.java
IntelliJ inspections corrected and some dependencies updated.
=> IntelliJ inspections corrected and some dependencies updated.

quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java
Fix for issue described in forum post: [Acceptor dropping logout messages](http://quickfix-j.364392.n2.nabble.com/Acceptor-dropping-logout-messages-td7579837.html).
The issue exists in 1.6.x so would be good to merge there too.
When a FIX acceptor is shutdown, a call is made to `SessionConnector.logoutAllSessions()`. This calls `Session.logout()` on all sessions in turn, regardless of prior status. The [logout()](https://github.com/quickfix-j/quickfixj/blob/06c312ef42bd53a99d997cee713dbdc9eab95fd5/quickfixj-core/src/main/java/quickfix/Session.java#L725) method is asynchronous and merely sets a private flag in `Session`. The actual logout message is sent later when the flag is picked up by a background thread (see [Session.next()](https://github.com/quickfix-j/quickfixj/blob/06c312ef42bd53a …
=> Fix for dropped logout message issue

quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java
Backport of PR #130 for QFJ 1.6.x branch.
=> Fix for dropped logout message issue (1.6.x)

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/WeekdaySessionSchedule.java, quickfixj-core/src/main/java/quickfix/WeekdaySessionScheduleFactory.java, quickfixj-core/src/test/java/quickfix/WeekdaySessionScheduleTest.java
This is a weekday based session schedule that can be used instead of `DefaultSessionSchedule`.
It uses a new session setting ID `Weekdays` which is a comma-delimited list of the days to _**start**_ the session on.
A standard western trading week example...
```
StartTime=22:05:00 UTC
EndTime=21:55:00 UTC
Weekdays=Sun,Mon,Tue,Wed,Thu
```
`StartDay `and `EndDay `are not used.
To tell QuickFIX/J to use the weekly schedule, a `WeekdaySessionScheduleFactory` instance must be passed to the `DefaultSessionFactory` constructor.
=> Weekday Session Schedule

quickfixj-core/pom.xml, quickfixj-messages/quickfixj-messages-fix40/pom.xml, quickfixj-messages/quickfixj-messages-fix41/pom.xml, quickfixj-messages/quickfixj-messages-fix42/pom.xml, quickfixj-messages/quickfixj-messages-fix43/pom.xml, quickfixj-messages/quickfixj-messages-fix44/pom.xml, quickfixj-messages/quickfixj-messages-fix50/pom.xml, quickfixj-messages/quickfixj-messages-fix50sp1/pom.xml, quickfixj-messages/quickfixj-messages-fix50sp2/pom.xml, quickfixj-messages/quickfixj-messages-fixt11/pom.xml
- only create and include javadoc for the specific FIX messages classes
- formerly every message javadoc package had all the docs for all messages included
- same for the core module javadoc package
=> fix javadoc generation for release

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java
The Acceptor sessions should get re-enabled if socket was disconnected during logout.
When the following disconnect code runs it skips re-enable the acceptor session.
if (!hasResponder()) {
if (!ENCOUNTERED_END_OF_STREAM.equals(reason)) {
getLog().onEvent("Already disconnected: " + reason);
}
return;
}
=> Re-enabled acceptor sessions in finally block

quickfixj-core/src/main/java/quickfix/FileStore.java, quickfixj-core/src/test/java/quickfix/FileStoreTest.java
* When a session window is not 'open', the quickfix timer thread will try to reset the filestore, which also initialises the creation time on the filestore.
* When there is another thread that tries to login (outside the session 'open' window), that thread will try to write something to the filestore, namely the header info, such as sequence number
* If the operation is interleaved in the following manner:
1. Quickfix timer thread closes the underlying filestore
2. Thread that accepts the login attempt to update the sequence number (which happens to be using buffered output stream, by the way)
3. Quickfix timer thread tries to close the underlying filestore again
Then the 3rd step above will fail. As part of the close, standard Java buffered output stream will see if there is anything on …
=> QFJ-902: Fixing a bug with attempt to close stream multiple times

quickfixj-dictgenerator/src/main/java/org/quickfixj/dictgenerator/Generator.java, quickfixj-dictgenerator/src/main/java/org/quickfixj/dictgenerator/Repository.java
I was creating a dictionary from a repository and got:
- NullpointerExceptions because NotReqXML was written with wrong letter case
- NoSuchElementException because it was not finding the session messages.
This change gives better errors in both cases, so that it is easier to find the reason of the problem.
=> Better error messages in dictionary generator

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java
This PR fixes the following problem:
- Field "F" belongs to component "C"
- Field "F" is marked as req'd within the component "C"
- Component "C" belongs to repeating group "G"
- Component "C" is marked as req'd within the group "G"
Expected: field "F" is req'd within the group "G", but validation ignores it.
For my own reference: PROM-4700.
=> Required component in group

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
**Example**
Session configuration snippet:
```
SocketConnectHost=host_0
SocketConnectPort=port_0
SocketConnectHost1=host_1
SocketConnectPort1=port_1
StartTime=07:30:00
EndTime=17:30:00
```
**Issue**
FIX session establishes connection to host_0 at 07:30:00
FIX session disconnects at 17:30:00
Next day FIX session established connection to host_1 at 07:30:00, but it is expected to be host_0
For my own reference: PROM-4719
=> After scheduled logout/disconnection FIX session starts connection attempts from the 1st host on the list

quickfixj-core/src/main/java/quickfix/SocketAcceptor.java, quickfixj-core/src/main/java/quickfix/SocketInitiator.java
- try to stop processing messages before removing Sessions
- this has now the same order as on the ThreadedSocketInitiator/Acceptor
=> Changes to stop() method of SocketAcceptor and SocketInitiator

quickfixj-core/src/main/java/quickfix/FieldMap.java, quickfixj-core/src/test/java/quickfix/FieldMapTest.java
Adds single method to FieldMap to retrieve an Optional<String> value for a tag number. Added test to FieldMapTest also.
I am having a problem with builds in Travis with tests. Based on a comment on the email list I am assuming that is related to other work.
=> Add getOptionalString + unit test to FieldMap

quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/test/java/quickfix/MessageTest.java
Header field present in FIX spec but missing in QFJ
See: http://fiximate.fixtrading.org/latestEP/en/FIX.5.0SP2_EP236/tag1156.html
=> Add new header field to header list: ApplExtID

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
@chrjohn This is the slightly blunt approach. You mentioned a better approach would be to increment only if the sequence number was right. I'm happy for you to update this PR.
I've written a test for it though - that should pass with/without your tweak I think.
=> Don't increment sequence number on rejected logon

quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/MessageTest.java
- added method Message.toRawString() which returns the message string as it was passed to the Message class
- in case of errors: log raw message data instead of incompletely parsed message
- added unit test
- improved some log messages in Session class
=> QFJ-940 - Event log omits parts of received message in case of validation errors

quickfixj-core/src/main/java/quickfix/DefaultMessageFactory.java, quickfixj-core/src/main/java/quickfix/MessageFactory.java, quickfixj-core/src/main/java/quickfix/MessageUtils.java, quickfixj-core/src/test/java/quickfix/DefaultMessageFactoryTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/ATMessageCracker.java
The background for this change is described in [QFJ-888](https://www.quickfixj.org/jira/browse/QFJ-888).
Changes are as follows:
1. Added a new create method to `MessageFactory` which accepts an `ApplVerID`. The default behavior of the new method is to call `MessageFactory.create(beginString, msgType)` in order to maintain backwards compatibility.
2. Modified `MessageUtils.parse` to call the new create method, passing in the `ApplVerID` acquired from the incoming message or the session. Other calls to `MessageFactory.create` have remained as-is.
3. Added a new constructor to `DefaultMessageFactory` which accepts an `ApplVerID` value to be used as the default when `create(beginString, msgType)` or `create(beginString, null, msgType)` is called. The existing constructor calls the new one, …
=> QFJ-888: DefaultMessageFactory does not support FIX5.0 SP1/2

quickfixj-core/src/main/java/quickfix/JdbcLog.java
I discovered this bug while trying to set different JDBC tables for different sessions.
=> Some calls to isSetting() don't specify the sessionID

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/SocketAcceptor.java, quickfixj-core/src/main/java/quickfix/SocketInitiator.java, quickfixj-core/src/main/java/quickfix/ThreadedSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/ThreadedSocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java, quickfixj-core/src/test/java/org/quickfixj/jmx/mbean/session/SessionAdminTest.java, quickfixj-core/src/test/java/quickfix/DefaultSessionFactoryTest.java, quickfixj-core/src/test/java/quickfix/FileLogTest.java, quickfixj-core/src/test/java/quickfix/JdbcLogTest.java, quickfixj-core/src/test/java/quickfix/SessionDisconnectConcurrentlyTest.java, quickfixj-core/src/test/java/quickfix/SessionDisconnectTest.java, quickfixj-core/src/test/java/quickfix/SessionResetTest.java, quickfixj-core/src/test/java/quickfix/SessionTest.java, quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java, quickfixj-core/src/test/java/quickfix/mina/ThreadPerSessionEventHandlingStrategyTest.java, quickfixj-core/src/test/java/quickfix/mina/acceptor/AcceptorIoHandlerTest.java, quickfixj-core/src/test/java/quickfix/mina/acceptor/DynamicAcceptorSessionProviderTest.java
- added logic to unregister Session to Session.close() method
- changed some tests to use try-with-resources on Session and to close used Sessions in general
- changed Connector implementations to clean up used Sessions on stop
- changed AbstractSocketInitiator to clean up internal map of initiators on stop
- added Initiator/Acceptor tests to ensure Sessions are unregistered on stop
=> Cleanup Sessions on stop

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
**SSLCertificateTest** fails quite often on Travis.
I was able to recreate **SSLCertificateTest** false positive failing tests locally using the same Travis CI Docker image snapshot as https://travis-ci.org/quickfix-j/quickfixj worker - **travisci/ci-garnet:packer-1512502276-986baf0**.
It seems that sometimes MINA produces exceptions other than SSLHandshakeException, where **org.apache.mina.filter.ssl.SslFilter#exceptionCaught(NextFilter nextFilter, IoSession session, Throwable cause)** can stop executing the filter chain (it actually has a special handling routine for **WriteToClosedSessionException**) , hence the exception is never captured by **SSLCertificateTest**.
_22:17:21.792 [NioProcessor-8] INFO  q.m.s.SSLCertificateTest$TestInitiator - …
=> improving flaky SSLCertificateTest

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java
Data dictionary validation is format independent now. The following tags are not allowed to be empty (with exception to \<header/> and \<trailer/> for FIX version 5.0 and higher).
- \<header/>
- \<trailer/>
- \<fields/>
- \<message/>
- \<messages/>
=> QFJ-932 - data dictionary validation format independent

quickfixj-core/src/main/java/quickfix/mina/QueueTracker.java, quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/TestConnection.java
- introduced SessionConnector.closeManagedSessionsAndDispose which makes an effort to close all managed sessions and disposes the IoService
- used new method in Acceptor, Initiator and TestConnection (used for acceptance tests)
NOTE: this also needs MINA 2.0.17 (#177 ), otherwise there still might be hangs when trying to dispose the IoService.
See https://issues.apache.org/jira/browse/DIRMINA-1076
=> QFJ-942: Observing hangs in dispose() on stop()

quickfixj-core/src/main/java/quickfix/SessionSettings.java, quickfixj-core/src/main/java/quickfix/mina/ssl/SSLSupport.java
Hi,
`FieldConvertError` is not being thrown in `getString` method. 
Regards,
Martin
=> Update getString signature in SessionSettings

quickfixj-core/src/main/java/quickfix/Message.java
as discussed here: 
[#39](https://github.com/quickfix-j/quickfixj/commit/6229d0722d8c6f6e7b2b251772a92caf2f4bdc25#commitcomment-28912357)
=> replaced Message.indexOf and Message.lastIndexOf by JDK-built-in methods

quickfixj-core/src/test/java/quickfix/SessionTest.java, quickfixj-core/src/test/java/quickfix/mina/SingleThreadedEventHandlingStrategyTest.java, quickfixj-core/src/test/java/quickfix/mina/acceptor/DynamicAcceptorSessionProviderTest.java
- minor corrections
- amended some tests
=> minor unit test changes

quickfixj-core/src/test/java/quickfix/FileLogTest.java, quickfixj-core/src/test/java/quickfix/LogUtilTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/AcceptanceTestSuite.java
- some unit tests did not reset it which lead to errors depending on test order
- e.g. ResynchTest and AcceptanceTests were failing constantly on my machine because LogUtilTest did not reset
the SystemTimeSource and as a result the Session did not send out any heartbeats
=> Correct handling of SystemTimeSource in tests

quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.modified.xml, quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.xml
AllocationInstruction and SettlementInstructions had duplicate fields
declared in their FIX schemas (AccruedInterestAmt and SettlInstSource)
respectively. We have removed those declarations that
were incorrect according to the FIX protocol
=> [Tom/Andrey] remove duplicate field definitions in fix44 xml spec

quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java
Make sure QF_SESSION attribute gets removed in any case. SingleThreadedEventHandlingStrategy.onMessage() might throw an Exception.
=> Minor cleanup in AbstractIoHandler.sessionClosed()

quickfixj-core/src/main/java/quickfix/SocketAcceptor.java, quickfixj-core/src/main/java/quickfix/SocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java, quickfixj-core/src/main/java/quickfix/mina/ThreadPerSessionEventHandlingStrategy.java, quickfixj-core/src/test/java/quickfix/mina/SingleThreadedEventHandlingStrategyTest.java
- Reverted changes from #192 since we actually want to process all messages on stop().
=> Corrections to SingleThreadedEventHandlingStrategy, SocketAcceptor/Initiator

pom.xml
`mvn package -PskipBundlePlugin` can be used to speed up the build when no bundle MANIFEST is needed, i.e. when you do not want to use the resulting JARs in an OSGi environment.
=> Add profile skipBundlePlugin to speed up build

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java, quickfixj-core/src/main/java/quickfix/InvalidMessage.java, quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/main/java/quickfix/MessageUtils.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java, quickfixj-core/src/test/java/quickfix/SessionFactoryTestSupport.java, quickfixj-core/src/test/java/quickfix/SessionTest.java, quickfixj-core/src/test/java/quickfix/mina/acceptor/AcceptorIoHandlerTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/AcceptanceTestSuite.java, quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/rejectGarbledMessages/fix50/QFJ950-RejectGarbledMessages.def
Provide configuration to have garbled messages rejected instead of ignored.
=> QFJ-950 reject garbled messages

quickfixj-core/src/main/java/org/quickfixj/CharsetSupport.java, quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/test/java/quickfix/MessageTest.java
The optimizations in commit 6229d0722d8c6f6e7b2b251772a92caf2f4bdc25 cause a regression where using fields with a non-default charset such as UTF-8 causes message corruption (even if the charset is properly set via CharsetSupport.setCharset()).
Further, the test that caught this regression (MessageTest.testMessageWithEncodedField via its helper method) was modified in the same commit to work around the test failure, so that the test passes but the bug still occurs in real applications.
=> QFJ-965 Fixed regression when using non-default charset

README.md, quickfixj-core/src/main/doc/usermanual/usage/receiving_messages.html, quickfixj-core/src/main/java/quickfix/ApplicationExtendedFunctionalAdapter.java, quickfixj-core/src/main/java/quickfix/ApplicationFunctionalAdapter.java, quickfixj-core/src/main/java/quickfix/FromAdminListener.java, quickfixj-core/src/main/java/quickfix/FromAppListener.java, quickfixj-core/src/main/java/quickfix/ToAppListener.java, quickfixj-core/src/test/java/quickfix/ApplicationExtendedFunctionalAdapterTest.java, quickfixj-core/src/test/java/quickfix/ApplicationFunctionalAdapterTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/ATMessageCracker.java
Provides adapter implementation of quickfix.Application and quickfix.ApplicationExtended that
1. allows registering multiple listeners for each operation (e.g. onLogon, onCreate) separately using Java 8's functional interfaces like Consumer, BiConsumer and Predicate. FromAdmin, FromApp and ToApp requires custom interfaces due to checked Exceptions. Also allows removing registered listeners.
2. invokes each registered listeners in a FIFO manner
3. for Predicate, it fail-fast when encounters the first Predicate returning false
4. for checked Exception listeners, it fail-fast when encounters the first Exception thrown
5. is completely optional to Quickfix users
6. is backward compatible
7. is thread-safe with the use of CopyOnWriteArrayList
8. does not add extra lib dependency
=> Functional adapters for Application and ApplicationExtended interfaces

quickfixj-core/src/main/java/quickfix/Application.java, quickfixj-core/src/main/java/quickfix/Message.java
This addresses the longstanding thread safety issue with DecimalFormat: http://sourceforge.net/mailarchive/forum.php?thread_name=1F6BAA78-6704-418C-8EDE-88FDCFFB9938%40parityenergy.com&forum_name=quickfixj-users
In the event it's already being used by people in a multi-threaded fashion this should make it more performant too because there's now one per thread rather than just one.
=> Make DecimalFormat ThreadLocal to fix potential thread safety problems

quickfixj-messages/quickfixj-messages-fix50/src/main/resources/FIX50.xml
Not big deal, but I fixed it. Somehow field order in AllocGrp was wrong in FIX50.xml file. In files for SP1 & SP2 it seems to be correct. 
Verified with: 
* Compared with FIX50.xml from http://www.quickfixengine.org/
* Compared with Fiximate https://fiximate.fixtrading.org/legacy/index.html
=> QFJ-811: Wrong field order in AllocGrp

quickfixj-core/src/main/java/quickfix/mina/acceptor/AcceptorIoHandler.java, quickfixj-core/src/main/java/quickfix/mina/initiator/InitiatorIoHandler.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorStub.java, quickfixj-core/src/test/java/quickfix/mina/acceptor/AcceptorIoHandlerTest.java, quickfixj-core/src/test/java/quickfix/mina/initiator/InitiatorIoHandlerTest.java
* Added the same test for all garbled messages that we have in AcceptorIoHandler
* I used Optional, but I couldn't use ifPresent block because this block of code is throwing checked exception
* In AcceptorIoHandler theoretically we could have the same issue, but check for message type is 'guarded' by session check 
```java
Session qfSession = (Session) protocolSession.getAttribute(SessionConnector.QF_SESSION);
if (qfSession == null) {
if (message.getHeader().getString(MsgType.FIELD).equals(MsgType.LOGON)) {
```
I don't know if it is valid use case that we could receive GarbledMessage before Logon message. If it is valid then I can adjust this class as well.
=> QFJ-976: GarbledMessage without MsgType

quickfixj-core/pom.xml
We shouldn't have to do anything since we are not using `SslFilter.USE_NOTIFICATION`
https://mina.apache.org/mina-project/2.1-vs-2.0.html
=> Upgrade MINA to 2.1.3

quickfixj-core/src/main/java/quickfix/DataDictionary.java
DataDictionary keeps some data in Map<IntStringPair, .V> structures. A new instance of IntStringPair is created every time to search the value in the map. When parsing market data (with a lot of repeating groups) it causes a lot of IntStringPair allocations (see the attached profiler screenshot, taken after ~1000 MarketDataSnapshotFullRefresh messages received).
Changing implementation to Map<Integer, Map<String, V>> nested maps allows to get rid of IntStringPair at all. The results are on another screenshot.
=> Optimize DataDictionary

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
... they are disabled in newer JDKs due to security concerns so we should not be suggesting that this is supported.
https://bugs.openjdk.java.net/browse/JDK-8211883
=> Remove tests with anonymous cipher suites

quickfixj-core/src/main/java/quickfix/Session.java
It's misleading to suggest we're sending a closed range request when instead we're sending an open ended request.
=> Provide correct end sequence number sent in request in logs

quickfixj-core/src/main/doc/usermanual/usage/sending_messages.html
There seems to have been a side effect from the QuickFix C++ Manual. I've updated the example code which was not changed to Java.
=> Fix Sending Messages Example Code in User Manual

quickfixj-core/src/main/java/quickfix/Session.java
This applies a fix from quickfix's main repository https://github.com/quickfix/quickfix/commit/5fb3d4ffc44775295d5525fb30335d57e869f27e.
=> Persistence is done before sending and will fail if message cannot be stored or sequence number cannot be incremented.

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java, quickfixj-core/src/test/java/quickfix/PausableThreadPoolExecutor.java
Fixes #240 
I've added unit tests for DataDictionary to verify this refactor doesn't change it's public API. Unfortunately this is as far as I was able to take this - not quite sure how to construct testcase for the actual race.
=> Calculating orderedFieldsArray eagerly to avoid concurrency problems (QFJ-971)

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java
- this is useful for mapping from/to the XML representation obtained
from `Message.toXML()`
- since the DataDictionary is kind of a memory hog we do not store the
values in yet another HashMap (which would cause Node objects to be created) but iterate over the entries on each call to `getValue(int, String)`
-- it is up to the user's application to cache the returned values if desired
=> Add method to DataDictionary to get the value for a given enum value name

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java, quickfixj-core/src/main/java/quickfix/Field.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionFactoryTestSupport.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
Adds possibility to specify tags via setting `LogonTag` or `LogonTag<n>`.
Example:
```
LogonTag=553=user
LogonTag1=554=password 
```
It is checked whether a data dictionary is present to determine whether the specified tag is a header field. Otherwise it is put into the body of the message.
=> Add custom tags to Logon message.

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/SessionState.java, quickfixj-core/src/test/java/quickfix/MockSystemTimeSource.java, quickfixj-core/src/test/java/quickfix/SessionFactoryTestSupport.java, quickfixj-core/src/test/java/quickfix/SessionStateTest.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
Fixes QFJ-375
**Changes**
- session timeout multiplier is configurable (default values retained)
- documentation update
=> QFJ-375 - configurable timeout multiplier

quickfixj-core/src/main/java/quickfix/MessageUtils.java, quickfixj-core/src/test/java/quickfix/MessageUtilsTest.java
=> Only check for ApplVerID on Logon and application messages

quickfixj-core/src/main/java/quickfix/FieldMap.java, quickfixj-core/src/main/java/quickfix/MessageComponent.java, quickfixj-core/src/test/java/quickfix/MessageComponentTest.java
**Changes**
- Custom FIX tags are copied to "parent" components.
Unfortunately it is not possible to do a reverse operation as the custom fields copied to "parent" would pollute every child component when retrieving it via "get*" methods. This is something that we don't want, especially when is an existing test case `quickfix.MessageTest#testComponent`.
Arguably we could change the class generation and add extra "get*" methods with additional arguments indicating that all (or selected ones) fields from "parent" components should be copied, but I think it might be a little overhead. The first attempt was done in https://github.com/quickfix-j/quickfixj/pull/210, but I think this is unnecessary clutter.
I updated the javadoc for `quickfix.MessageComponent#copyFrom` and …
=> QFJ-636 - custom fields in component blocks are not added to parent

quickfixj-core/src/main/java/quickfix/mina/ProtocolFactory.java, quickfixj-core/src/test/java/quickfix/mina/ProtocolFactoryTest.java
Fixes https://github.com/quickfix-j/quickfixj/issues/295
Opening as a DRAFT before we gather the test evidence.
@curdreinert
Would you be able to build or test directly from branch? At the moment I'm using CCProxy for Windows, but I struggle to get either SOCKS or HTTP method to work (most likely a setup issue). Also, what OS and proxy software are you using? I will have a look again in the evening/tomorrow.
=> Preferred proxy authentication methods removed

quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.xml
Fixes QFJ-741
Seems like 99 - Other should be available since FIX 4.4
http://fixwiki.org/fixwiki/AllocCancReplaceReason/99_Other
=> QFJ-741 - missing value in AllocCancReplaceReason in FIX44.xml

quickfixj-core/src/main/java/quickfix/mina/acceptor/AcceptorIoHandler.java
To be able to see the source of multiple (i.e. excess) Logon attempts at a glance.
We currently log the remote address when the TCP connection is established, but in a separate message.
```
MINA session created: local=/xxxx:1234, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/yyyy:5678
```
However, this information might be hard to find in the log file when many messages are exchanged on the already connected session. Moreover, there might be additional connection attempts by more than one counterparty.
This PR will add the remote address to the log message, for example:
```
Multiple logons/connections for this session are not allowed. Closing connection from /127.0.0.1:54082 since session is already established from /127.0.0.1:54058
```
=> Log remote address on multiple Logon

quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java, quickfixj-core/src/main/java/quickfix/mina/NetworkingOptions.java, quickfixj-core/src/main/java/quickfix/mina/ProtocolFactory.java, quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
As mentioned in the original JIRA certain socket options set after `org.apache.mina.core.service.IoHandlerAdapter#sessionOpened` event might not be configured properly as they require to be set before call to listen() or connect() e.g. SO_REUSEADDR, SO_RCVBUF.
**Changes**
- `quickfix.mina.NetworkingOptions` will be applied before sockets around bound. 
This chagne makes "SocketReceiveBufferSize" configuration TCP handshake advertisement correct and it will allow finer tweaking based on network capacity, system requirements etc.
Increasing the "SocketReceiveBufferSize" above 64KB was working correct for **initiators** already, but was fixed as part of https://issues.apache.org/jira/projects/DIRMINA/issues/DIRMINA-1123 for **acceptors**.
Please be aware that there is still an issue for …
=> QFJ-456 - NetworkingOptions should be applied before the socket is connected

quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/ConnectorAdmin.java, quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/SocketAcceptorAdmin.java, quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/SocketAcceptorAdminMBean.java, quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/SocketInitiatorAdmin.java, quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/SocketInitiatorAdminMBean.java, quickfixj-core/src/main/java/org/quickfixj/jmx/openmbean/CompositeTypeFactory.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java, quickfixj-core/src/test/java/org/quickfixj/jmx/openmbean/CompositeTypeFactoryTest.java
Fixes https://github.com/quickfix-j/quickfixj/issues/304
**Changes**
- broken open beans fixed "Acceptor/AcceptorAddresses", "Acceptor/Sessions", "Initiator/Sessions" by https://github.com/quickfix-j/quickfixj/pull/205
- removed broken "Initiator/Endpoints" and replaced with "Initiator/InitiatorAddresses" (have been broken for a while)
=> Composite jmx attributes fix

quickfixj-codegenerator/src/main/java/org/quickfixj/codegenerator/GenerateMojo.java, quickfixj-codegenerator/src/main/java/org/quickfixj/codegenerator/MessageCodeGenerator.java, quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/Fields.xsl, quickfixj-core/src/main/doc/usermanual/usage/codegen.html, quickfixj-core/src/main/java/quickfix/UtcTimeField.java, quickfixj-core/src/main/java/quickfix/UtcTimeOnlyField.java, quickfixj-core/src/main/java/quickfix/UtcTimeStampField.java
Fixes #310
Added support for setting a default UtcTimestampPrecision in the
quickfixj-codegenerator Maven plugin. The default applies to the
following classes and their generated sub classes.
- UtcTimeField
- UtcTimeOnlyField
- UtcTimeStampField
=> Set UtcTimestampPrecision in codegenerator

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java, quickfixj-core/src/test/java/quickfix/MessageTest.java, quickfixj-core/src/test/resources/FIX_External_DTD.xml
Fixes https://github.com/quickfix-j/quickfixj/issues/306
**Changes**
- data dictionary blocks external dtd/schema properties only when using JDK Xerces implementation
- removed dtd/schema properties from `quickfix.Message#toXML(quickfix.DataDictionary)` - it is not required as we are neither loading, nor validation against schemas
- unit tests
**Comments**
- dtd/schema properties probably are not required in `org.quickfixj.codegenerator.MessageCodeGenerator` as it uses files that belong to the codebase, so changes pointing to external dtd/schema would be visible in PRs (the only reason I can think to keep it there is if somebody is dependent on `org.quickfixj:quickfixj-codegenerator` directly in their project to customise message generation)
- this change fixes Xerces compatiblity …
=> Fixing Xerces dtd/schema backward compatibility

quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/session/SessionAdmin.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/SessionStateListener.java, quickfixj-core/src/test/java/quickfix/SessionDisconnectConcurrentlyTest.java, quickfixj-core/src/test/java/quickfix/SessionResetTest.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java, quickfixj-core/src/test/java/quickfix/UnitTestApplication.java
Fixes #313
See #313 for additional details
=> Expose sequence recovery data via SessionStateListener

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
This should fix  `quickfix.mina.ssl.SSLCertificateTest` test failures in https://github.com/quickfix-j/quickfixj/pull/319.
Seems that in future versions of Java `javax.net.ssl.SSLSession#getPeerCertificateChain` gets deprecated and starts throwing exceptions. We should use `javax.net.ssl.SSLSession#getPeerCertificates`.
=> Replacing peer certificate chain with peer certificates method call

.github/workflows/maven.yml
According to https://github.com/actions/virtual-environments/issues/1499 this should help with Maven connection timeouts.
=> Maven connection timeout workaround

quickfixj-core/src/test/java/quickfix/MessageTest.java
There are some tricky XML scenarios to test across different Java version.  At the moment the test is disabled for the GitHub build actions to pass.
More information at https://github.com/quickfix-j/quickfixj/pull/322
=> Temporary disabling tricky test

quickfixj-core/src/main/java/quickfix/ThreadedSocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java
- was only possible for SocketInitiators (non-threaded) up to now
- see #254 / #255 for original issue
- improved error message in AbstractSocketAcceptor/Initiator
=> Add reconnectThreads functionality to ThreadedSocketInitiator.

quickfixj-core/src/main/java/quickfix/SocketAcceptor.java, quickfixj-core/src/main/java/quickfix/SocketInitiator.java, quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java
To prevent errors like the following in CI workflow (mostly on Windows):
`Error:    SingleThreadedEventHandlingStrategyTest.shouldCleanUpInitiatorQFJMessageProcessorThreadAfterStop:294 ConcurrentModification`
But could probably also happen in the wild.
=> Made start/stop of SocketInitiator/SocketAcceptor thread-safe.

quickfixj-core/src/main/resources/config/sql/oracle/event_log_table.sql, quickfixj-core/src/main/resources/config/sql/oracle/messages_log_table.sql
Closes #348 
Add Oracle DDLs to create `event_log` and `messages_log` tables.
This is possible to test running one [Oracle 12c R2](https://hub.docker.com/_/oracle-database-enterprise-edition) container and following these steps:
https://hub.docker.com/_/oracle-database-enterprise-edition
```
docker login
docker run -d -it -p 1521:1521 --name oracle-db store/oracle/database-enterprise:12.2.0.1-slim
```
Example with DBeaver:
- Host: localhost
- Port: 1521
- Database: ORCLCDB
- Type: SID
- Username: sys
- Password: Oradoc_db1
- Role: sysdba
```sql
alter session set "_ORACLE_SCRIPT"=true;
```
```sql
create user QUICKFIX identified by QUICKFIX;
```
```sql
GRANT ALL PRIVILEGES TO QUICKFIX;
```
Example with DBeaver:
- Host: localhost
- Port: 1521
- Database: ORCLCDB
- Type: SID
- Username: …
=> add oracle ddl tables event_log and messages_log (QFJ-979)

README.md
Closes #350 
Small correction in `README.md` on the `toAdmin` item
```
This allows you to add fields before an adminstrative message before it is sent out.
```
```
This allows you to add fields to an administrative message before it is sent out.
```
=> change toAdmin text

quickfixj-core/src/main/doc/usermanual/usage/application.html
A small correction on the toadmin description in the user manual documentation.
This was talked on https://github.com/quickfix-j/quickfixj/issues/237
Local test:
```
This allows you to add fields before an adminstrative message before it is sent out.
```
```
This allows you to add fields to an administrative message before it is sent out.
```
=> Corrects the toAdmin description in the user manual documentation

quickfixj-core/src/main/doc/usermanual/installation.html
Closes #343 
Change from:
```
There are various command-line switches you can pass to ant to modify the produced behavior:
```
To:
```
There are various command-line switches you can pass to mvn to modify the produced behavior:
```
=> Change reference from ant do mvn in the user manual

quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/session/SessionAdmin.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/SessionState.java, quickfixj-core/src/test/java/quickfix/SessionResetTest.java, quickfixj-core/src/test/java/quickfix/SessionTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/ATApplication.java
Fixes #244
_This is my first attempt to contribute to the core QuickFIX/J codebase. Please read the described changes bellow and review the changes thoroughly._
**quickfix.Session#reset()**
* When there is a need to logout: Instead of calling `quickfix.Session#generateLogout()` followed by `quickfix.Session#disconnect(String, boolean)`, set `quickfix.Session#isResetStatePending` flag and call `quickfix.Session#logout(String)` followed by `quickfix.Session#generateLogout(String)`. `quickfix.Session#logout(String)` will set `quickfix.Session#enabled` to `false` and `quickfix.Session#generateLogout(String)` will send a `Logout` message. The flag `quickfix.Session#isResetStatePending` is checked when `Logout` response is received or when timing out waiting for a `Logout` response.
* Only call …
=> Wait for Logout response or timeout before disconnect on session reset

quickfixj-core/src/main/java/quickfix/SessionSettings.java, quickfixj-core/src/test/java/quickfix/SessionSettingsTest.java
Closes #367 
As stated in the #367 issue, I only created two new constructors in the SessionSettings class, one with `(List<String)` and the other with `(List<String>, Properties)`.
I tested it locally between my application and the executor and everything went fine.
```java
@ConfigProperty(name = "quickfix")
List<String> quickfixSessionSettings;
...
SessionSettings sessionSettings = new SessionSettings(quickfixSessionSettings);
```
```
[default]
[session]
BeginString=FIX.4.4
SenderCompID=BANZAI
TargetCompID=EXEC
ConnectionType=initiator
StartTime=00:00:00
EndTime=00:00:00
ReconnectInterval=5
HeartBtInt=30
SocketConnectHost=localhost
SocketConnectPort=9880
ScreenLogShowHeartBeats=Y
```
```
[DEFAULT]
[SESSION]
BeginString=FIX.4.4
SenderCompID=BANZAI
SocketConnectPort=9880 …
```
=> Add List<String> constructor to SessionSettings

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/main/java/quickfix/SessionStateListener.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java
Fixes #342 
Added `SessionStateListener.onConnectException()` which gets called from `IoSessionInitiator.handleConnectException()`
Added `Session.getStateListener()`.
=> Add SessionStateListener.onConnectException()

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionTest.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java
Also see #359 
When Logon sequence was initiated externally. i.e. counterparty initiated Logout sequence, acceptor should still accept subsequent Logon attempts from that counterparty.
=> Preventing the acceptor session from accepting Logon message when Logout was initiated locally.

quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java
Changed unit test to use localhost and VM_PIPE to hopefully fix flaky test behaviour in GitHub CI builds
In some builds there was no connection attempt (when it was expected each second) for the duration of the unit test (which runs about 3 seconds).
=> SessionStateListener.onConnectException - unit test correction

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/Acceptor.java, quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java, quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java, quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java, quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java
Fixes #375 
- Now exceptions (e.g. SSL-related) will be ignored when `ContinueInitializationOnError=Y` and hence
will not prevent initialization of other sessions on the same Initiator/Acceptor.
=> Consider ContinueInitializationOnError on creation of IoSessionInitiator/IoAcceptor

quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java
=> minor addition to error message

quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
QFJ-266 and QFJ-822 previously made changes around the clearing of cached DNS resolution.  These resolved issues relating to a cached non-resolution, and enforcing re-resolution after a failure to connect.  However there are other cases that this does not cover such as a counter-party changing their DNS entries but leaving something listening at the old location.  In this case you can still connect successfully but not get a response to your Logon message.  As this is not a connection error, the QFJ-822 enhancement is not triggered.
All cases can be covered by following the QFJ-266 solution but ignoring whether the address was previously resolved or unresolved.  Simply clear the cached DNS info on every connect.
=> Always re-resolve `SocketAddress` on reconnect.

quickfixj-core/src/main/java/quickfix/BytesField.java, quickfixj-core/src/test/java/quickfix/FieldTest.java
**Changes**
- `quickfix.BytesField` uses `org.quickfixj.CharsetSupport`
This is the last remaining item from QFJ-789, so possibly this could be closed as well.
=> QFJ-684 - added charset support to `BytesField`

quickfixj-examples/executor/src/main/java/quickfix/examples/executor/Application.java
Starting from FIX.4.3, ExecType.PARTIAL_FILL and ExecType.FILL were removed
and replaced by ExecType.TRADE.
=> Set correct value for ExecType in ExecutionReport (Executor example application)

quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java, quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionFactoryTestSupport.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
=> allow sending unchanged message in `Session#send`

quickfixj-core/src/test/java/quickfix/UnitTestApplication.java, quickfixj-core/src/test/java/quickfix/mina/SessionConnectorTest.java
Sometimes `SessionConnectorTest.testConcurrentAccess()` triggered an `ArrayIndexOutOfBoundsException` because sessions were added concurrently.
```
[INFO] Running quickfix.mina.SessionConnectorTest
java.lang.ArrayIndexOutOfBoundsException: Index 627 out of bounds for length 549
at java.base/java.util.ArrayList.add(ArrayList.java:487)
at java.base/java.util.ArrayList.add(ArrayList.java:499)
at quickfix.UnitTestApplication.onCreate(UnitTestApplication.java:79)
at quickfix.DefaultSessionFactory.create(DefaultSessionFactory.java:249)
at quickfix.mina.SessionConnector.createSession(SessionConnector.java:182)
at quickfix.mina.SessionConnectorTest.lambda$testConcurrentAccess$1(SessionConnectorTest.java:308)
```
=> Made `UnitTestApplication` thread-safe.

quickfixj-core/src/main/java/quickfix/FieldMap.java, quickfixj-core/src/test/java/quickfix/FieldMapTest.java
=> Remove group entry entirely when removing a group

quickfixj-core/src/main/java/quickfix/DataDictionary.java, quickfixj-core/src/main/java/quickfix/FieldMap.java, quickfixj-core/src/main/java/quickfix/Message.java
FieldMap already provides iterator() to inspect all fields, however does not implement Iterable - and so can't be used in for-each loop. This PR adds Iterable interface, as well as groupKeys() which exposes group keys as Iterable.
The motivation for the change is that in some cases it is useful to traverse message as a tree of key-value pairs - e.g. when visualising message structure in UI, or transforming it to another intermediate representation. Being able to iterate in a more idiomatic Collection-like way improves readability of such code.
I was thinking about marking iterator() and groupKeyIterator() as deprecated - I don't see any advantages of those methods over Iterable. In the end decided to not do this for the first cut, but they can be eventually retired.
=> Add methods to `FieldMap` API to make it usable in for-each loop

quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java, quickfixj-core/src/test/java/quickfix/test/acceptance/ATServer.java, quickfixj-core/src/test/java/quickfix/test/acceptance/ExpectMessageStep.java, quickfixj-core/src/test/java/quickfix/test/acceptance/TestConnection.java, quickfixj-core/src/test/java/quickfix/test/util/ReflectionUtil.java, quickfixj-core/src/test/java/quickfix/test/util/StackTraceUtil.java
Java built-in way will be used now via `StackTraceUtil.dumpStackTraces()`
=> Get rid of `ReflectionUtil.dumpStackTraces()`.

pom.xml
... for JDK9+ to prevent build runtime errors like these:
```
Error: Exception in thread "pool-15-thread-2" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
at org.apache.mina.core.buffer.AbstractIoBuffer.flip(AbstractIoBuffer.java:462)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:534)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$1200(AbstractPollingIoProcessor.java:68)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1224)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1213)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcess …
```
=> use maven.compiler.release

quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java
... instead of `VM_PIPE` which caused occasional test failures.
Interestingly mostly the Ubuntu JDK8 build was affected by this. The underlying problem seems to be somewhere in the `VM_PIPE` implementation of MINA. :man_shrugging:
=> Changed SocketAcceptorTest to use `SOCKET`

.github/dependabot.yml
See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Added dependabot for GitHub Actions and Maven

quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java
In cases where the connection needs to be closed immediately (unknown session or invalid Logon message) we will still use `closeNow()`.
There were some SSL-related tests which failed due to messages not being flushed. See https://github.com/quickfix-j/quickfixj/pull/441/commits/4345ca0c2def0e5cc747fb9afd55bb2c5b222b37
=> Use `ioSession.closeOnFlush()` where sensible

quickfixj-core/src/main/java/quickfix/field/converter/UtcTimestampConverter.java
Signed-off-by: Baoyi Chen <chen.bao.yi@qq.com>
Original PR: #456
=> Optimize `convertToLocalDateTime` method

quickfixj-core/src/main/java/quickfix/field/converter/AbstractDateTimeConverter.java, quickfixj-core/src/main/java/quickfix/field/converter/IntConverter.java, quickfixj-core/src/main/java/quickfix/field/converter/UtcTimestampConverter.java, quickfixj-core/src/test/java/quickfix/FieldConvertersTest.java
Put `parseLong` and `parseInt` methods into `IntConverter`.
=> Cleaned up conversion of `int` and `long` in converters

quickfixj-core/src/main/java/quickfix/Session.java, quickfixj-core/src/test/java/quickfix/SessionTest.java
Fixes https://github.com/quickfix-j/quickfixj/issues/474 - 
verify() method call moved further up in nextLogon() to prevent seqNumber resets over invalid logins.
=> Validate `Logon` message before acting upon `ResetMsgSeqNum` flag

quickfixj-core/src/main/java/quickfix/NumbersCache.java, quickfixj-core/src/main/java/quickfix/field/converter/AbstractDateTimeConverter.java, quickfixj-core/src/main/java/quickfix/field/converter/IntConverter.java, quickfixj-core/src/test/java/quickfix/FieldConvertersTest.java
Replaced `Long.toString()` by call to `NumbersCache.get()` to prevent unnecessary allocation for integers ranging from 0 to 99999.
Improved performance of integer parsing for integers shorter than `Integer.MAX_VALUE`.
Heuristic: since we have no range check in our `parseInt()` we only parse values which have at least one digit less than `Integer.MAX_VALUE` and leave longer Strings to `Integer.parseInt()`.
NB: we must not simply reject strings longer than `MAX_VALUE` since they could possibly include an arbitrary number of leading zeros.
=> Improve `IntConverter` performance

quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java, quickfixj-core/src/test/java/quickfix/mina/LostLogoutTest.java, quickfixj-core/src/test/java/quickfix/mina/LostLogoutThreadedTest.java
=> Use dynamic port for `LostLogoutTest`, `LostLogoutThreadedTest`, `SocketAcceptorTest`

quickfixj-core/src/main/java/quickfix/FieldMap.java, quickfixj-core/src/main/java/quickfix/SessionRejectReasonText.java, quickfixj-core/src/test/java/quickfix/FieldMapTest.java, quickfixj-core/src/test/java/quickfix/MessageTest.java
fixes #458  -  Raising this PR to trigger the discussion.
If we decide to create new `SessionRejectReason.NULL_DATA_FOR_VALUE`, then we might need to adjust **quickfixj-messages** XML for all versions - _e.g. 40, 41, 42, 43, 44, 50, 50sp1, 50sp2, fixt11_ - since `SessionRejectReason` seems to be generated based on them.
For now, decided to keep **OTHER**.
**Alternative**: create specific e.g. `NullFieldValueException` similar to `FieldNotFound`
@chrjohn please review and let me know your thoughts on how to implement it properly.
=> `FieldMap` - enhancing thrown exception for null values

quickfixj-core/src/main/java/quickfix/Message.java, quickfixj-core/src/test/java/quickfix/MessageTest.java
Enhancements made to correctly parse Header fields found in the body of a message.
Fixes #468
=> Enhanced logic around the `ValidateFieldsOutOfOrder` setting 

quickfixj-distribution/src/main/assembly/distribution.xml, quickfixj-examples/pom.xml
See https://github.com/quickfix-j/quickfixj/discussions/566#discussioncomment-5113958 and following comments.
This should correct the `NullPointerException` during builds with the `-PskipBundlePlugin` profile.
=> Remove `slf4j-jdk14` from `examples` and `distribution` module

quickfixj-core/src/main/java/quickfix/FileUtil.java, quickfixj-core/src/test/java/quickfix/FileUtilTest.java
Fixes #653 based on commits by @david-gibbs-ig on #460
=> Correct `Resource not found` in `FileUtilTest`

quickfixj-core/src/main/java/quickfix/FileUtil.java, quickfixj-core/src/test/java/quickfix/FileUtilTest.java
Same PR as #654 on master
* update FileUtil to resolve new 403 error for requests with User-Agent header
* Updated User-Agent value for FileUtil
* Added check for HttpUrlConnection to changes done in #460
=> Correct `Resource not found` in `FileUtilTest` (#654) on QFJ 2.3.x

pom.xml
Security vulnerabilities should be fixed in recent maven plugin versions.
Needs #712
=> Removed guava dependency

quickfixj-base/src/main/java/org/quickfixj/CharsetSupport.java, quickfixj-core/src/main/java/quickfix/CachedFileStore.java, quickfixj-core/src/main/java/quickfix/FileStore.java, quickfixj-core/src/test/java/quickfix/AbstractMessageStoreTest.java, quickfixj-core/src/test/java/quickfix/FieldTest.java, quickfixj-core/src/test/java/quickfix/FileStoreTest.java, quickfixj-core/src/test/java/quickfix/MessageTest.java, quickfixj-core/src/test/java/quickfix/SleepycatStoreTest.java, quickfixj-core/src/test/java/quickfix/mina/message/FIXMessageDecoderTest.java, quickfixj-core/src/test/java/quickfix/mina/message/FIXMessageEncoderTest.java
Fixes https://github.com/quickfix-j/quickfixj/issues/650
=> `FileStore` message length fix

quickfixj-base/src/main/java/quickfix/DataDictionary.java, quickfixj-base/src/test/java/quickfix/DataDictionaryTest.java
Fixes #636 
There is no reason why a message shouldn't have only header and trailer, see message type `n`.
https://fiximate.fixtrading.org/legacy/en/FIX.4.4/body_5255110.html
Header and trailer should not allowed to be empty. Unit tests need to be updated.
=> `DataDictionary`: removed check for empty message body

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
This is related to discussion https://github.com/quickfix-j/quickfixj/discussions/760
Added a test scenario where an acceptor is configured to support 2 sessions - one with SSL and one without. No problems found so far and this scenario works as expected.
=> Additional test scenario with acceptor running mixed sessions

quickfixj-core/src/test/java/quickfix/JdbcLogTest.java, quickfixj-core/src/test/java/quickfix/JdbcTestSupport.java
... due to `AbstractMethodError`
- java.lang.AbstractMethodError: org.hsqldb.jdbc.jdbcConnection.isValid(I)Z
- moved definition of connection test query to common method for unit tests
Don't know why this only failed on Ubuntu, though.
```
Error:    SessionTest.testSessionRegisteredCorrectly:1849 » AbstractMethod Receiver class org.hsqldb.jdbc.jdbcConnection does not define or inherit an implementation of the resolved method 'abstract boolean isValid(int)' of interface java.sql.Connection.
```
=> Corrected failing `SessionTest` on Ubuntu runner

quickfixj-core/src/main/java/quickfix/SessionSettings.java, quickfixj-core/src/test/java/quickfix/SessionSettingsTest.java
Fixes #751 
To support dynamically modifying session configurations, I want to add function `removeSection` in SessionSettings
This feature is particularly useful in scenarios where configuring dynamic session, and there's a need to remove outdated or unnecessary settings without affecting the entire configuration.
(using sessionID or property)
=> Added function `removeSection` in `SessionSettings`

quickfixj-core/src/main/java/quickfix/SessionSettings.java
I overlooked the fact that there were several sections with the same property key and value. 
Therefore, I've updated the removeSection method to handle multiple sections.
=> update removeSection method to remove sections with the same property key and value

quickfixj-core/src/main/java/quickfix/Session.java
UseDataDictionary=N , dataDictionaryProvider is null
Fixes #776
=> Correct NullPointerException on `UseDataDictionary=N` and FIXT session

.github/workflows/maven.yml
=> Use MacOS 13 for now for Java CI

quickfixj-core/pom.xml, quickfixj-core/src/main/java/quickfix/mina/CustomSslFilter.java, quickfixj-core/src/main/java/quickfix/mina/ProtocolFactory.java, quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java, quickfixj-core/src/test/java/quickfix/mina/SocksProxyServer.java, quickfixj-core/src/test/java/quickfix/mina/SocksProxyTest.java, quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
**Changes**
- added custom SSL wrapper to fix proxy connectivity before official MINA patch
- removed unused PROXY protocol type
- added SOCKS proxy server (via Netty)
- added Maven build extension to help build tests using Netty
- added SSL and non-SSL integration tests
=> Mina proxy handshake fix and proxy integration tests

quickfixj-core/src/main/java/quickfix/SystemTime.java, quickfixj-core/src/main/java/quickfix/UtcTimeStampField.java
`LocalDateTime.now(ZoneOffset)` is slow because a new `ConcurrentHashMap` object is allocated each time on ZoneRules instance creation, and SystemClock is instantiated in Java 8.
Benchmark results for Java 8
```
Benchmark                                                                                 Mode      Cnt        Score    Error   Units
LocalDateTimeInitBenchmark.withCachedClockWithOffset                                    sample  1291695      423.817 ± 66.584   ns/op
LocalDateTimeInitBenchmark.withCachedClockWithOffset:withCachedClockWithOffset·p0.00    sample               145.000            ns/op
LocalDateTimeInitBenchmark.withCachedClockWithOffset:withCachedClockWithOffset·p0.50    sample               148.000            ns/op …
```
=> Improve `UtcTimeStampField` instantiation time

quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/MessageCracker.xsl
=> `MessageCracker.xsl` optimization using `HashMap`

quickfixj-base/src/main/java/quickfix/field/converter/UtcTimestampConverter.java, quickfixj-base/src/test/java/quickfix/FieldConvertersTest.java, quickfixj-base/src/test/java/quickfix/FieldMapTest.java
=> check for leapsecond in `UTCTimestampConverter`

quickfixj-core/src/test/java/quickfix/SLF4JLogTest.java
Fixes #858. Registering the test handler seems to have side effects on other tests.
=> remove `TestHandler` after usage in `SLF4JLogTest`

.gitignore
I'm barely proficient with maven, but I'm pretty sure `.mvn/wrapper/maven-wrapper.jar` should be ignored.
And also vim `.swp` files.  (I can't be the only vim user in QF land, can I?)
=> gitignore vim `.swp` files and `maven-wrapper jar`

.github/workflows/maven.yml, quickfixj-codegenerator/pom.xml
- Replaced windows 2016 by windows latest (since 2016 was removed from the GHA runners)
- Replaced Ubuntu 18 by Ubuntu latest (since 18 was removed from the GHA runners)
- cherry picked commit 2e1a73fc06b88a7a16cb9b3a38651b2c75c2e752 to add the missing goal prefix
=> Fixes for the branch 2.3.x build

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
Small SSL test improvements.
**Changes**
- SNI algorithm should be set for two cases
- Oracle JVM gives slightly different error message for `quickfix.mina.ssl.SSLCertificateTest#shouldFailWhenHostnameDoesNotMatchServerName` test case (error message is prepended with exception class name)
expected: "No name matching localhost found"
actual: "java.security.cert.CertificateException: No name matching localhost found"
I think there are different messages in JVM's higher than > 17 which might require changes in the future
=> Fixing test assertion for different JVM's

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java, quickfixj-core/src/test/java/quickfix/mina/ssl/SecureSocketTest.java
Some small changes to tackle failing tests.
**Changes**
- added additional logging on Acceptor / Initiator shutdown for SSL test
- increased timeout for SecureSocketTest
=> Additional SSL test logging

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java, quickfixj-core/src/test/java/quickfix/test/util/SSLUtil.java
This will fix the SSL test suite for TLS v1.3.
**Changes**
- switching cipher suite and TLS version for `SSLCertificateTest` (see https://github.com/quickfix-j/quickfixj/pull/892)
- refactored some SSL util methods and extracted them to a separate class
- modified `assertNotAuthenticated` method
The problem with  authentication and TLS v1.3 seems to be with MacOS Java version 8 and 11 as it fails continuously with this combination (works fine with MacOS Java 17). I've seen it failing occasionally on Ubuntu.
The authentication actually works fine, but the assertions were not correct. Seeing `Certificate was authenticated` was misleading since the previous checks - `assertSslExceptionThrown`  and `assertNotLoggedOn` were successful, which means that SSL session was actually NOT  established …
=> Fixing test assertions for TLSv1.3

quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/BanzaiApplication.java
When I was testing the example, Banzai, I found an issue where it wouldn't update the new values in the UI when it receives a REPLACE ExecutionReport. It would retain its previous value. The new version handles and updates the order with the updated value.
=> Fixed Replace Order UI functionality in Banzai Example

.github/workflows/nightly-build.yml, README.md, pom.xml
Fixes #769 
I came across the discussions under https://github.com/quickfix-j/quickfixj/discussions/941 and the issue https://github.com/quickfix-j/quickfixj/issues/769 and had a look at the snapshot releases.
- A draft of a GitHub Actions pipeline that **builds with JDK 17** and **publishes to GitHub Packages**
- The pipeline is set to run on cron (1AM) and on new commits to master
- I tested the publishing to Packages [on my fork](https://github.com/krisbanas?tab=packages&repo_name=quickfixj). .
- The GitHub Packages repo indexes the artifacts as `3.0.0-SNAPSHOT` and keeps them timestamped under the hood.
- I set up a test Gradle project to test resolving the snapshot, it downloads the most recent artifact (upon forcing it to `--refresh-dependencies`).
- The pipeline uses …
=> Add nightly SNAPSHOT release to GitHub Packages

.github/workflows/nightly-build.yml
Fixes #966 
Used https://github.com/marketplace/actions/delete-old-packages since https://github.com/marketplace/actions/delete-package-versions only supports a single package.
With the current configuration the two most recent versions will be kept.
=> added action to delete old packages

.github/workflows/nightly-build.yml
Github Packages accumulates packages since each SNAPSHOT version has a new timestamp.
See https://github.com/actions/delete-package-versions/issues/71 or https://stackoverflow.com/questions/68521637/how-to-delete-old-snapshot-artifacts-from-github-packages
SNAPSHOT versions have a distinct timestamp in the repo, but the github action sees all these packages as belonging to the same version, so specifiying a minimum number of versions to keep does not work. So we simply tell the action to keep `0` versions.
To minimize the time in which there is no version available on github packages we will do:
- build QFJ (this takes about 20 minutes)
- delete packages
- deploy packages
=> completely delete SNAPSHOT packages before deploying new SNAPSHOT version

.github/workflows/codeql-analysis.yml, .github/workflows/maven.yml, .github/workflows/nightly-build.yml
we do not need the nightly build to run on `push`
we do not need the other builds to build on `schedule`
=> Update build jobs

quickfixj-core/pom.xml, quickfixj-core/src/main/doc/usermanual/usage/configuration.html, quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java, quickfixj-core/src/main/java/quickfix/mina/ssl/InitiatorSslFilter.java, quickfixj-core/src/main/java/quickfix/mina/ssl/SSLConfig.java, quickfixj-core/src/main/java/quickfix/mina/ssl/SSLSupport.java, quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java, quickfixj-core/src/test/java/quickfix/mina/ssl/SSLSupportTest.java, quickfixj-core/src/test/java/quickfix/test/util/SSLUtil.java
This is a backport of the fix for [#1036 ](https://github.com/quickfix-j/quickfixj/issues/1036) for QFJ 2.3.x
=> Backport of fix for SSL `server_name` extension value

quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java, quickfixj-core/src/main/java/quickfix/mina/initiator/InitiatorProxyIoHandler.java
Close is definitely not required here. At this stage the session is already closed. Close is idempotent so it has no effect.
Call stack.
- `quickfix.mina.AbstractIoHandler#sessionClosed`
- `quickfix.mina.initiator.InitiatorProxyIoHandler#sessionClosed`
- `org.apache.mina.core.filterchain.DefaultIoFilterChain.TailFilter#sessionClosed`
I created additional logging on a different branch to make sure that `org.apache.mina.core.session.IoSession#isClosing` is true every time we get here.
```
@Override
public void sessionClosed(IoSession ioSession) {
try {
Session quickFixSession = findQFSession(ioSession);
if (quickFixSession != null) {
eventHandlingStrategy.onMessage(quickFixSession, EventHandlingStrategy.END_OF_STREAM);
}
} catch (Exception e) {
throw e;
} finally {
Object oldAttribute = …
```
=> Remove unnecessary `IoSession.close()` for session that is already closed
