quickfix-j/quickfixj

quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java

Reverts quickfix-j/quickfixj#7

Revert "QFJ-822 Refresh DNS resolution info on connection error."

---

pom.xml

Bump SLF4J to 1.7.12 which has minor OSGI bundle fixes and few extra features

Bump SLF4J to 1.7.12 which has minor OSGI bundle fixes

---

pom.xml

Upgrade compiler plugin and increase max memory size for compilation

---

quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java

Reverts quickfix-j/quickfixj#8

Revert "Revert "QFJ-822 Refresh DNS resolution info on connection error.""

---

quickfixj-core/src/main/java/quickfix/mina/ssl/SSLConfig.java
quickfixj-core/src/main/java/quickfix/mina/ssl/SSLContextFactory.java
quickfixj-core/src/main/java/quickfix/mina/ssl/X509TrustManagerWrapper.java
quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
quickfixj-core/src/test/java/quickfix/mina/ssl/X509TrustManagerWrapperTest.java

Improvements made as suggested in https://github.com/quickfix-j/quickfixj/pull/49

Post QFJ-821 test improvements

---

pom.xml

command | gpg sign
------------ | -------------
mvn clean deploy -P release | no
mvn clean deploy -P release,sign | yes

QFJ-846 : Upload release to Maven/Sonatype (add signing profile)

---

pom.xml
quickfixj-core/pom.xml

Mina-core, Slf4j and Maven compiler plugin have been updated to latest

---

pom.xml
quickfixj-core/pom.xml

Most important:
* Mina-core 2.0.12
* Slf4j 1.7.16
You can cherry pick this commit to QFJ_1_6_X

Bump dependencies and plugins

---

pom.xml
quickfixj-core/src/main/java/quickfix/DataDictionary.java
quickfixj-messages/quickfixj-messages-fix40/pom.xml
quickfixj-messages/quickfixj-messages-fix41/pom.xml
quickfixj-messages/quickfixj-messages-fix42/pom.xml
quickfixj-messages/quickfixj-messages-fix43/pom.xml
quickfixj-messages/quickfixj-messages-fix44/pom.xml
quickfixj-messages/quickfixj-messages-fix50/pom.xml
quickfixj-messages/quickfixj-messages-fix50sp1/pom.xml
quickfixj-messages/quickfixj-messages-fix50sp2/pom.xml
quickfixj-messages/quickfixj-messages-fixt11/pom.xml

Extracted variable, bump slf4j and plugins versions.

Extracted variable, bump slf4j and plugins versions

---

quickfixj-core/src/test/java/quickfix/test/acceptance/resynch/ResynchTest.java
quickfixj-core/src/test/java/quickfix/test/acceptance/resynch/ResynchTestServer.java
quickfixj-core/src/test/java/quickfix/test/acceptance/timer/TimerTest.java
quickfixj-core/src/test/java/quickfix/test/acceptance/timer/TimerTestServer.java

...and organized the code a bit.

Fixed occasionally failing ResychTest and TimerTest

---

quickfixj-core/src/main/java/quickfix/ThreadedSocketInitiator.java
quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java
quickfixj-core/src/main/java/quickfix/mina/IoSessionResponder.java
quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java
quickfixj-core/src/test/java/quickfix/mina/IoSessionResponderTest.java

Patched classes provided with ticket that fixes #895 for 1.6.x

Fixes QFJ-895 for 1.6.x

---

pom.xml
quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java
quickfixj-core/src/main/java/quickfix/mina/ThreadPerSessionEventHandlingStrategy.java

@chrjohn please review and cherry pick if you feel is not good, one change is the closeOnFlush and the other pom changes.

Queues drain tweak and bump plugin versions.

---

quickfixj-codegenerator/src/main/resources/org/quickfixj/codegenerator/MessageSubclass.xsl
quickfixj-messages/quickfixj-messages-fix50sp2/src/main/resources/FIX50SP2.modified.xml

- integrated patch submitted by Scott Harrington

QFJ-876: Code Generator creates bad code for nested repeating groups

---

quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.modified.xml
quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.xml

- corrected FIX4.4 data dictionaries

QFJ-886: FIX44.xml InstrumentLeg Inconsistently Defined

---

pom.xml

Update slf4j-api to 1.7.22 and maven-compiler to 3.6.1

Update slf4j-api to 1.7.22 and maven-compiler to 3.6.1

---

quickfixj-core/src/main/java/quickfix/Connector.java
quickfixj-core/src/main/java/quickfix/SocketAcceptor.java
quickfixj-core/src/main/java/quickfix/SocketInitiator.java
quickfixj-core/src/main/java/quickfix/ThreadedSocketAcceptor.java
quickfixj-core/src/main/java/quickfix/ThreadedSocketInitiator.java
quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java
quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java
quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java
quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java
quickfixj-core/src/test/java/quickfix/mina/SingleThreadedEventHandlingStrategyTest.java

Based on #101 which has been submitted by @alphafoobar

QFJ-885 Logout message is not sent out

---

quickfixj-core/src/main/java/quickfix/Message.java
quickfixj-core/src/test/java/quickfix/MessageTest.java

- add repeating group regardless of wrong order (up to problematic field)

QFJ-792: Wrong order of fields in a repeating group makes the group ignored

---

pom.xml
quickfixj-codegenerator/pom.xml
quickfixj-core/src/main/java/quickfix/DataDictionary.java
quickfixj-core/src/main/java/quickfix/FieldMap.java
quickfixj-core/src/main/java/quickfix/SessionSettings.java
quickfixj-core/src/main/java/quickfix/mina/ThreadPerSessionEventHandlingStrategy.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java
quickfixj-examples/executor/src/main/java/quickfix/examples/executor/Executor.java
quickfixj-examples/ordermatch/src/main/java/quickfix/examples/ordermatch/OrderMatcher.java

JDK 8 tidy up, plugins and dependencies updates:
- Tidy up new code to be JDK 8 format.
- Updated plugins to latest.
- Update Slf4j to 1.7.25

JDK 8 tidy up, plugins and dependencies updates.

---

quickfixj-core/src/main/java/quickfix/Session.java
quickfixj-core/src/test/java/quickfix/SessionTest.java

- make sure that it is checked if session needs to be reset before processing Logon

QFJ-926: Session reset happens after logon

---

quickfixj-core/src/main/java/quickfix/Session.java

Test omitted as it's written using Java8 lambda's

change from https://github.com/quickfix-j/quickfixj/pull/118 on 1.6 branch

---

quickfixj-core/pom.xml
quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java
quickfixj-core/src/main/java/quickfix/mina/IoSessionResponder.java
quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AcceptorIoHandler.java
quickfixj-core/src/main/java/quickfix/mina/initiator/InitiatorIoHandler.java
quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java

- used distinct session log where possible
- introduced constant for attribute QFJ_RESET_IO_CONNECTOR
- generate FIX50SP2 fields as last step

some very minor refactorings

---

pom.xml
quickfixj-all/pom.xml
quickfixj-codegenerator/pom.xml
quickfixj-core/pom.xml
quickfixj-dictgenerator/pom.xml
quickfixj-distribution/pom.xml
quickfixj-examples/banzai/pom.xml
quickfixj-examples/executor/pom.xml
quickfixj-examples/ordermatch/pom.xml
quickfixj-examples/pom.xml
quickfixj-messages/pom.xml
quickfixj-messages/quickfixj-messages-all/pom.xml
quickfixj-messages/quickfixj-messages-fix40/pom.xml
quickfixj-messages/quickfixj-messages-fix41/pom.xml
quickfixj-messages/quickfixj-messages-fix42/pom.xml
quickfixj-messages/quickfixj-messages-fix43/pom.xml
quickfixj-messages/quickfixj-messages-fix44/pom.xml
quickfixj-messages/quickfixj-messages-fix50/pom.xml
quickfixj-messages/quickfixj-messages-fix50sp1/pom.xml
quickfixj-messages/quickfixj-messages-fix50sp2/pom.xml
quickfixj-messages/quickfixj-messages-fixt11/pom.xml

- usage of Java DateTime API, QFJ-873

changed version to 2.0.0-SNAPSHOT due to breaking API change (QFJ-873)

---

pom.xml
quickfixj-codegenerator/pom.xml
quickfixj-core/src/main/java/quickfix/JdbcStore.java
quickfixj-core/src/main/java/quickfix/Session.java
quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java
quickfixj-dictgenerator/pom.xml

Dependencies and plugins updated to latest and some IntelliJ inspections suggestions applied.

Dependencies and plugins updated to latest.

---

quickfixj-core/src/main/java/org/quickfixj/jmx/JmxExporter.java
quickfixj-core/src/main/java/org/quickfixj/jmx/mbean/connector/ConnectorAdmin.java
quickfixj-core/src/main/java/quickfix/CachedFileStore.java
quickfixj-core/src/main/java/quickfix/DefaultSessionSchedule.java
quickfixj-core/src/main/java/quickfix/Session.java
quickfixj-core/src/main/java/quickfix/SleepycatStore.java
quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java
quickfixj-core/src/main/java/quickfix/mina/IoSessionResponder.java
quickfixj-core/src/main/java/quickfix/mina/NetworkingOptions.java
quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java
quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AcceptorIoHandler.java
quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java
quickfixj-core/src/main/java/quickfix/mina/message/FIXMessageDecoder.java
quickfixj-core/src/main/java/quickfix/mina/ssl/SSLContextFactory.java
quickfixj-core/src/test/java/quickfix/SocketInitiatorTest.java
quickfixj-core/src/test/java/quickfix/UnitTestApplication.java
quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java
quickfixj-core/src/test/java/quickfix/mina/ssl/SecureSocketTest.java
quickfixj-core/src/test/java/quickfix/test/acceptance/ATServer.java
quickfixj-core/src/test/java/quickfix/test/acceptance/ConnectToServerStep.java
quickfixj-core/src/test/java/quickfix/test/acceptance/resynch/ResynchTestClient.java
quickfixj-examples/executor/src/main/java/quickfix/examples/executor/Application.java
quickfixj-examples/executor/src/main/java/quickfix/examples/executor/Executor.java

- https://www.slf4j.org/faq.html#logging_performance

Changed logging to use formatting anchor {} where applicable.

---

quickfixj-core/src/main/doc/usermanual/installation.html

I've switched to maven central, and dropped the links to marketcetera.org, since the site seems to be down

Various fixes in install.html

---

quickfixj-core/pom.xml

To hopefully prevent test failures on Windows

added -Djava.net.preferIPv4Stack=true to test config

---

quickfixj-core/src/test/java/quickfix/mina/ssl/SecureSocketTest.java

forward caught exception to next filter in SecureSocketTest

---

quickfixj-core/src/main/java/quickfix/IncorrectTagValue.java
quickfixj-core/src/main/java/quickfix/InvalidMessage.java
quickfixj-core/src/main/java/quickfix/Message.java

- added constructor with cause for InvalidMessage
- corrected usage of problematic value for IncorrectTagValue

Minor changes to IncorrectTagValue and InvalidMessage

---

quickfixj-core/src/main/java/quickfix/Message.java

...(96) without RawDataLength(95)
- improved error message

QFJ-944 Misleading error message on Logon with tag RawData

---

quickfixj-core/pom.xml

to be merged when it has been relased
Then also https://www.quickfixj.org/jira/browse/QFJ-937 (MaxScheduledWriteRequests is ineffective) can be closed.

Update MINA to 2.0.17

---

quickfixj-core/src/main/java/quickfix/FieldMap.java
quickfixj-core/src/test/java/quickfix/FieldMapTest.java

Hi,
this PR adds `getOptionalDecimal` method to `FieldMap`. It is a follow up to #162.
Regards,
Martin

Add getOptionalDecimal to FieldMap

---

quickfixj-core/src/test/java/quickfix/mina/ssl/SSLCertificateTest.java

https://travis-ci.org/quickfix-j/quickfixj/builds/379656032

prevent NPE in SSLCertificateTest as encountered in Travis build

---

quickfixj-core/src/main/java/quickfix/mina/SingleThreadedEventHandlingStrategy.java

- implemented interrupt() when DedicatedThreadExecutor is used
- this should fix failing SocketInitiatorTests as observed in https://travis-ci.org/quickfix-j/quickfixj/builds/384335297

SingleThreadedEventHandlingStrategy thread should be interrupted on stop()

---

quickfixj-core/src/main/java/quickfix/UtcDateField.java
quickfixj-core/src/main/java/quickfix/UtcDateOnlyField.java
quickfixj-core/src/main/java/quickfix/UtcTimeField.java
quickfixj-core/src/main/java/quickfix/UtcTimeOnlyField.java
quickfixj-core/src/main/java/quickfix/UtcTimeStampField.java
quickfixj-core/src/test/resources/logging.properties

- added ZoneOffset.UTC where applicable

 QFJ-961 Constructors for UtcDate/Time fields should return date in UTC

---

quickfixj-core/src/main/java/quickfix/SLF4JLog.java
quickfixj-core/src/test/java/quickfix/SLF4JLogTest.java

I think I probably need to revert some tests too. It's a pure revert - we can probably keep some bits.
We should probably also workout how to ensure it's not broken in the future somehow.

QFJ-983 Revert changes made to try to optimise SLF4JLog

---

README.md

Notes on reporting security issues.

---

quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java

I'm going through open JIRAs to see what still needs fixing.
Just added a unit test case suggested in the JIRA. The issue was fixed by https://github.com/quickfix-j/quickfixj/pull/148.
I think the JIRA ticket should be marked as fixed in QFJ 2.1.0

QFJ-951 - test case covering JIRA description

---

quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java

Fixed last LGTM alert - unnecessary null check.

LGTM alert fix

---

quickfixj-core/src/main/doc/usermanual/usage/acceptor_failover.html
quickfixj-core/src/main/doc/usermanual/usage/configuration.html
quickfixj-core/src/main/java/quickfix/CachedFileStore.java
quickfixj-core/src/main/java/quickfix/FileStore.java
quickfixj-core/src/test/java/quickfix/AbstractMessageStoreTest.java

including failover, SocketAcceptPort and SocketAcceptAddress

QFJ-22 update documentation for Acceptor configurations

---

quickfixj-core/src/main/doc/usermanual/usage/configuration.html
quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java
quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java
quickfixj-core/src/test/java/quickfix/MultiAcceptorTest.java

Support ContinueInitializationOnError for Acceptors

---

quickfixj-core/pom.xml

**Changes**
- updated mina-core to new version. 
Can we merge this? There was a fix made in this MINA release that was requested by me and it will allow to fix QFJ-456.

Updated mina-core dependency

---

pom.xml

See https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250

update to JUnit 4.13.1

---

quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.modified.xml

Add 99/Other to 796/AllocCancReplaceReason for FIX44.modified.xml.

---

quickfixj-core/pom.xml

Updated berkeleydb / sleepycat dependency

---

README.md
quickfixj-core/src/main/doc/usermanual/installation.html

Closes #364 
Please feel free to suggest any change.

Adding tips for importing the project into the IDE

---

quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java
quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java

AcceptorTemplate sessions do no longer work

---

quickfixj-core/src/main/java/quickfix/DataDictionary.java
quickfixj-core/src/main/java/quickfix/FixVersions.java
quickfixj-core/src/test/java/quickfix/DataDictionaryTest.java

`DataDictionary`: provide methods to get service and extension pack.

---

quickfixj-core/src/main/java/quickfix/mina/message/FIXMessageDecoder.java
quickfixj-core/src/test/java/quickfix/mina/message/FIXMessageDecoderTest.java

Prevent infinite loop on parsing invalid FIX message.

---

.github/workflows/maven.yml

See https://github.com/actions/virtual-environments/issues/4312
Updated to ubuntu-latest while I'm at it.

Use "latest" OS runners

---

quickfixj-core/src/main/doc/usermanual/usage/configuration.html

Per the code, you can specify different SocketConnectProtocols for each fallback.

Add config for `SocketConnectProtocol` fallback

---

quickfixj-messages/quickfixj-messages-fix42/src/main/resources/FIX42.xml

As per FIX4.2 documentation, https://www.onixs.biz/fix-dictionary/4.2/msgType_G_71.html

Changed field 35 value "G" description to "ORDER_CANCEL_REPLACE_REQUEST"

---

quickfixj-core/src/main/java/quickfix/SessionSettings.java

fixes #378 
@chrjohn please, let me know if there any other changes I couldn't catch.
Also, if we should extend this issue to other classes - I can do it

`SessionSettings` - Cleaning up `getBool()` exception handling

---

pom.xml

Decouple maven version (which is enforced) from maven libs.

Update maven libs independent from maven

---

.github/workflows/maven.yml

added 3rd parameter for configure-pagefile-action

---

.github/workflows/codeql-analysis.yml
.github/workflows/maven.yml
.gitignore
.mvn/jvm.config
.mvn/wrapper/maven-wrapper.properties
README.md
mvnw
mvnw.cmd
quickfixj-core/src/main/doc/usermanual/installation.html

Fixes #740 
TODO
- update build docs (especially xpath options can be removed)

Add usage of maven wrapper

---

quickfixj-examples/banzai/src/main/java/quickfix/examples/banzai/Banzai.java

allow people to change the most "business-logicy" parts of banzai by extending the Banzai class and one of OrderTableModel, ExecutionTableModel, and BanzaiApplication

increase banzai's OCP a little

---

.mvn/wrapper/maven-wrapper.properties
pom.xml

https://github.com/quickfix-j/quickfixj/pull/826#issuecomment-2175711410
Thanks @cstamas

Update Maven libs and plugin

---

quickfixj-core/src/main/java/quickfix/Log.java
quickfixj-core/src/main/java/quickfix/LogUtil.java
quickfixj-core/src/main/java/quickfix/Session.java
quickfixj-core/src/main/java/quickfix/SessionSettings.java
quickfixj-core/src/main/java/quickfix/mina/IoSessionResponder.java
quickfixj-core/src/main/java/quickfix/mina/SessionConnector.java
quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java
quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java
quickfixj-core/src/test/java/quickfix/SessionSettingsTest.java
quickfixj-core/src/test/java/quickfix/mina/IoSessionResponderTest.java

Changed logging to use session-specific log where applicable

---

quickfixj-base/src/main/java/quickfix/DataDictionary.java
quickfixj-base/src/main/java/quickfix/Message.java
quickfixj-core/src/main/java/quickfix/SessionSettings.java

... for better performance
Also see #559

replaced some `Integer.parseInt()` by `IntConverter.convert()`

---

quickfixj-base/src/main/java/quickfix/FieldMap.java
quickfixj-base/src/main/java/quickfix/Message.java
quickfixj-base/src/main/java/quickfix/MessageUtils.java

- in places which get called frequently

Replaced `Integer.toString()` by `NumbersCache.get()` where applicable

---

.github/workflows/maven.yml
quickfixj-core/src/test/resources/logging.properties

Fixing CI test logging.
Seems to work. Have a look at my CI branch build:
https://github.com/the-thing/quickfixj/actions/runs/12946375432/job/36110769380

Fixing CI logging configuration

---

pom.xml

Remove leftovers from proxool

---

.devcontainer/devcontainer.json

try to get an environment running, where Junie can build QFJ successfully...

use basic container
